[template]
keys = [
  "/firehose"
]
owner = "root"
mode = "0644"
src = "firehose-haproxy.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
check_cmd  = "/usr/sbin/haproxy -f {{ .src }} -c"
reload_cmd = "/usr/bin/pkill -SIGUSR2 ^haproxy-systemd.*"
